#+title: Fast-Fourier Transform and Schönhage-Strassen algorithm implementation
#+author: Kuporosov Ilya
#+email: yurxo@bk.ru

This repository contains C++ implementations of the Cooley-Tukey Fast Fourier Transform
algorithm and Schönhage-Strassen Large Integers Multiplication algorithm, which uses the
Fast Fourier Transform. Source files are in the ./fft-and-ssa directory.

A visual demonstration of the Fast Fourier Transform algorithm is presented in the
./fft-demo-py directory and is written in Python programming language. There is also a
comparison between the FFT algorithm built into the numpy library and the implemented one.

* How to build

Go to ./fft-and-ssa directory and run ~make~ command. By default, it uses ~c++~ compiler
(system default) and produces ~out-main~ binary, but should work with both ~g++~ and ~clang++~.
To specify the compiler, run ~make CPP=<compiler>~, e.g. ~make CPP=g++~.

* GitIgnore

#+begin_src txt :tangle .gitignore
/.venv
/fft-and-ssa/*.o
/fft-and-ssa/out-main
#+end_src

* License (The MIT License)

#+begin_src txt :tangle LICENSE
Copyright 2023 Kuporosov Ilya <yurxo@bk.ru>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+end_src
